const roles = [
  {
    name: "Loup Garou",
    tour: 4,
    tourProtectedLG: Infinity,
    immuniseSorciere: false,
    cycle: "Nuit",
    firstHeure: "minuit",
    valueHeure: 24,
    description: `
    Chaque nuit les loups-garous se concertent pour dépecer un habitant. Leur objectif est de dévorer tout le village. 
    Attention certains habitants sont protégés aux crocs et aux griffes de ces puissantes bêtes.`,
    quantity: 2,
    image: "/images/Loup Garou.png",
    accessoire: {
      name: "Griffes & Crocs",
      nbUsage: Infinity,
      image: "",
    },
  },
  {
    name: "Citrouille maudite",
    tour: 1,
    tourProtectedLG: 0,
    immuniseSorciere: false,
    cycle: "Jour/nuit",
    firstHeure: "19h",
    valueHeure: 19,
    description: `
    La citrouille maudite protège un habitant la nuit, mais si elle est éliminée au vote du village, 
    elle révèlera le camp d'un des habitants.`,
    quantity: 1,
    image: "/images/Citrouille maudite.png",
    accessoire: {
      name: "Charme de protection",
      nbUsage: Infinity,
      image: "",
    },
  },
  {
    name: "Zombie",
    tour: 0,
    tourProtectedLG: 0,
    immuniseSorciere: true,
    cycle: "Jour",
    firstHeure: "1h",
    valueHeure: 25,
    description: `
    Si éliminé par le vote du village ou par la potion de la sorcière, le zombie revient à la vie la nuit suivante.
    Mais attention il ne résiste aucunement à la morsure des garous.`,
    quantity: 1,
    image: "/images/Zombie.png",
    accessoire: {
      name: "Charme anti-magie",
      nbUsage: 1,
      image: "",
    },
  },
  {
    name: "Vampire",
    tour: 3,
    tourProtectedLG: 0,
    immuniseSorciere: false,
    cycle: "Nuit",
    firstHeure: "23h30",
    valueHeure: 23.5,
    description: `Le vampire choisit un habitant pour l'ensorceler. Ce dernier ne pourra donc pas voter contre lui 
    lors du prochain vote du village.`,
    quantity: 1,
    image: "/images/Vampire.png",
  },
  {
    name: "Fantôme",
    tour: 0,
    tourProtectedLG: Infinity,
    immuniseSorciere: false,
    cycle: "Jour",
    firstHeure: "17h",
    valueHeure: 17,
    description: `Le fantôme est immunisé contre les attaques des garous. 
    Sa mort ne peut provenir que d'un vote du village ou d'une potion de la sorcière.`,
    quantity: 1,
    image: "/images/Fantôme.png",
    accessoire: {
      name: "Masque du défunt",
      nbUsage: Infinity,
      image: "",
    },
  },
  {
    name: "Sorcière",
    tour: 2,
    tourProtectedLG: 0,
    immuniseSorciere: false,
    cycle: "Nuit",
    firstHeure: "18h",
    valueHeure: 18,
    description: `Dispose d'une potion pour éliminer un habitant. Cette potion est à usage unique, 
    alors ne la gaspillez pas !`,
    quantity: 1,
    image: "/images/Sorcière.png",
    accessoire: {
      name: "Potion tueuse",
      nbUsage: 1,
      image: "",
    },
  },
  {
    name: "Momie",
    tour: 0,
    tourProtectedLG: 1,
    immuniseSorciere: false,
    cycle: "Jour",
    firstHeure: "20h",
    valueHeure: 20,
    description: `Ses sparadraps la protège d'une attaque de garous. De plus, lorsqu'elle est éliminée 
    par le vote du village, elle peut entraver les pouvoirs d'un habitant`,
    quantity: 1,
    image: "/images/Momie.png",
    accessoire: {
      name: "Sparadraps",
      nbUsage: 1,
      image: "",
    },
  },
];
